baseURL = 'https://liam8888999.github.io/'
languageCode = 'en-us'
title = 'Recipe Book'
theme = 'lugo'

[params]
  favicon = "favicon.svg"
  stylesheet = "style.css"
  indexarticles = 50
  taglist = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
